spring:
  datasource:
    url: jdbc:mysql://dbcadastro.c68hy0koptsq.us-east-1.rds.amazonaws.com:3306/cadastro
    username: admin
    password: Legosite1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  error:
    include-binding-errors: never

